notifications:
    email: false

os:
    - linux

dist: xenial

language: generic

before_install:
    - set -e
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - sh ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update -y conda
    - sudo apt-get update
    - sudo apt-get install -y gcc cmake
    # - sudo apt-get install -y --no-install-recommends texlive-full
    # - sudo apt-get install -y --no-install-recommends texlive-base texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra
    # - kanji-config-updmap-sys ipaex
    - conda install --yes sphinx
    - ROOTDIR=`pwd`

install:
    - mkdir build
    - cd build
    - cmake ../
    # - VERBOSE=1 make
    - VERBOSE=1 make hello doc-jp-html doc-en-html


script:
    - ctest -V
    ## This is a pull request, finish.
    - ["$TRAVIS_PULL_REQUEST" != "false" ] && travis_terminate 0
    ## This is neither master nor tag, finish.
    - (["$TRAVIS_BRANCH" != "master" ] && [ -z "$TRAVIS_TAG" ] ) && travis_terminate 0
    - cd $ROOTDIR
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch # --unshallow
    - git checkout gh-pages
    - DOCDIR=docs/${TRAVIS_BRANCH}
    - mkdir -p ${DOCDIR}/jp/
    - mkdir -p ${DOCDIR}/en/
    - cp -r build/doc/jp/html/* ${DOCDIR}/jp
    # - cp -r build/doc/jp/pdf/test_travis.pdf ${DOCDIR}/jp
    - cp -r build/doc/en/html/* ${DOCDIR}/en
    # - cp -r build/doc/en/pdf/test_travis.pdf ${DOCDIR}/en
    - git add ${DOCDIR}
    - |
      if (git commit -m "Update by TravisCI"); then
        git push "https://${GH_TOKEN}@github.com/yomichi/test-travis.git" gh-pages:gh-pages --follow-tags > /dev/null 2>&1
      else
        true
      fi

