os:
    - linux

language: generic

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - sh ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update -y conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

    - sudo apt-get update
    - sudo apt-get install -y gcc cmake
    - sudo apt-get install -y --no-install-recommends texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra
    - kanji-config-updmap-sys ipaex
    - conda install --yes sphinx

install:
    - mkdir build
    - cd build
    - cmake ../
    - VERBOSE=1 make

script:
    - ctest -V

